#!/bin/sh

xsetroot -solid black

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

test -f "$sysresources" && xrdb -merge "$sysresources"

test -f "$sysmodmap" && xmodmap "$sysmodmap"

test -f "$userresources" && xrdb -merge "$userresources"

test -f "$usermodmap" && xmodmap "$usermodmap"

xset +fp /home/strake/.fonts
setxkbmap -option compose:caps
xset m 7/4 0
xset r rate 225 50

exec i3
